### PR TITLE
build.sbt: Add root project definition

### PR DESCRIPTION
**Pull request by dnltz**
I'm not sure if this is correct or I'm doing something wrong with sbt, but this is required to include this project via `dependsOn(...)`.

### CODE REVIEW

**Comment by Dolu1990** [comment]
I'm not sure to understand, what is the initial issue ?

I cloned SBT, and can run sbt commands for the crypto module via 

```scala
sbt
...
crypto/compile             <- for instance
```

**Comment by dnltz** [comment]
Tried to include it in another project via `dependsOn`, as you mentioned in the issue, and it does not work. It tries to download the maven project by the variable name `spinalCrypto`:
```
    ).dependsOn(spinalCrypto)

lazy val spinalCrypto = RootProject(file("../SpinalCrypto/"))
```

**Comment by dnltz** [comment]
Side note: I tried to include it the same way I include VexRiscv.

**Comment by Dolu1990** [comment]
Ahhh i see the issue
VexRiscv main folder is the the module. While SpinalCrypto is a sbt project with a inner module (crypto).
So it is a bit different. :/

To be honnest it is a bit weird. i don't know why it was setup as this

I think your PR try to workaround the issue, but maybe the best would be to keep your root project def, but delete all the 
lazy val crypto = (project in file("crypto"))  related stuff ?

**Comment by dnltz** [comment]
@Dolu1990  Do you mean like this?

**Comment by Dolu1990** [comment]
Yes :D

**Comment by Dolu1990** [comment]
@Snoopy87 Would it make sense for you ? Or we missed on reason ?

**Pull request merged**
